default:
  replicaCount: 1
  image:
    repository: grafana/grafana  
    pullPolicy: IfNotPresent  
    tag: "10.2.3"  

  service:   
    type: ClusterIP    
    port: 3000
  
  # This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ingress:
    enabled: true
    className: "nginx"
    annotations: 
      kubernetes.io/ingress.class: nginx    
    hosts:
       - host: grafana.meuteste.com
         paths:
           - path: /
             pathType: Prefix
    tls: []
 
  
  resources:   
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi 
 
  
  autoscaling:
     enabled: false
     minReplicas: 1
     maxReplicas: 100
     targetCPUUtilizationPercentage: 80
  
  volumes: []
 
  volumeMounts: []
 
  nodeSelector: {}
  
  tolerations: []
  
  affinity: {}
