grafana:
  enabled: true
  replicaCount: 1
  image: grafana/grafana
  tag: 10.2.3
  service:
    port: 3000
    type: ClusterIP
  persistentVolumeClaim:
    enabled: true
    name: grafana-pvc
    storage: 5Gi
    storageClassName: local-storage  # Especificando sua storage class
  ingress:
    enabled: true
    hosts:
      - host: grafana.meuteste.com
        paths:
          - path: /

python-api:
  enabled: true
  replicaCount: 2
  image: python:3.9
  tag: latest
  service:
    port: 5000
    type: ClusterIP
  persistentVolumeClaim:
    enabled: false  # API Python normalmente não precisa de armazenamento persistente
  ingress:
    enabled: true
    hosts:
      - host: python-api.meuteste.com
        paths:
          - path: /
