my-chart:  
    replicaCount: 1    
    image:
      repository: grafana/loki
      tag: "1.4.0"
      pullPolicy: IfNotPresent
  
    adminPassword: admin  # (ou use secret)
  
    service:
      type: ClusterIP
      port: 3000
  
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - host: grafana.meuteste.com
          paths:
            - path: /
              pathType: Prefix
      tls: []
  
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: local-storage
      accessModes:
        - ReadWriteOnce
        
    prometheus:
         replicaCount: 1
         image:
           repository: prom/prometheus
           tag: "v2.33.1"
           pullPolicy: IfNotPresent
       
         service:
           type: ClusterIP
           port: 9090
       
         ingress:
           enabled: true
           className: nginx  # ou conforme seu Ingress Controller
           annotations:
             nginx.ingress.kubernetes.io/rewrite-target: /
           hosts:
             - host: prometheus.meuteste.com
               paths:
                 - path: /
                   pathType: Prefix
           tls: []  # Adicione se usar TLS
       
         resources:
           requests:
             memory: "1Gi"
             cpu: "50m"
           limits:
             memory: "2Gi"
       
         persistence:
           enabled: true
           size: 10Gi
           storageClass: local-storage
           accessModes:
             - ReadWriteOnce
        
 
