chart-default:
  name: grafana
  image:
    repository: grafana/grafana
    tag: 10.2.3
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: grafana.meuteste.com
        paths:
          - path: /
            pathType: Prefix


   
