apps:
  grafana:
    enabled: true
    replicaCount: 1
    image:
      repository: grafana/grafana
      tag: "10.2.3"
      pullPolicy: IfNotPresent
    service:
      port: 3000
      type: ClusterIP
    autoscaling:
       enabled: false
    persistentVolumeClaim:
      enabled: true
      name: grafana-pvc
      storage: 5Gi
      storageClassName: local-storage
      accessModes:
        - ReadWriteOnce
    ingress:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: grafana.meuteste.com
          paths:
            - path: /
              pathType: Prefix
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "200m"

  python-api:
    enabled: true
    replicaCount: 2
    image:
      repository: python
      tag: "3.9"
      pullPolicy: IfNotPresent
    service:
      port: 5000
      type: ClusterIP
      
    autoscaling:
       enabled: false
       
    ingress:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: python-api.meuteste.com
          paths:
            - path: /
              pathType: Prefix
    livenessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      limits:
        memory: "256Mi"
        cpu: "300m"
      requests:
        memory: "128Mi"
        cpu: "100m"
