my-chart:  
    replicaCount: 1    
    image:
      repository: grafana/loki
      tag: "1.4.0"
      pullPolicy: IfNotPresent
  
    adminPassword: admin  # (ou use secret)
  
    service:
      type: ClusterIP
      port: 3000
  
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - host: grafana.meuteste.com
          paths:
            - path: /
              pathType: Prefix
      tls: []
  
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: local-storage
      accessModes:
        - ReadWriteOnce
        
 
