my-chart:
  grafana:
    #enabled: true
    image:
      repository: grafana/grafana
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - host: grafana.meuteste.com
          paths:
            - path: /
              pathType: Prefix
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    persistence:
      enabled: true
      storageClassName: local-storage
      size: 2Gi
      accessModes:
        - ReadWriteOnce
    admin:
      existingSecret: ""
      user: admin
      password: admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-operated:9090
            isDefault: true
  
  prometheus:
    #enabled: true
    #server:
    image:
      repository: prometheus/prometheus
      tag: v2.33.1
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9090
      targetPort: 9090
      name: prometheus-operated
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: prometheus
      selector:
        matchLabels:
          app: prometheus
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - host: prometheus.meuteste.com
          paths:
            - path: /
              pathType: Prefix
    persistence:
      enabled: true
      storageClass: local-storage
      size: 20Gi
      accessModes:
        - ReadWriteOnce
  
  kube-state-metrics:
    enabled: true
    image:
      repository: quay.io/coreos/kube-state-metrics
      tag: v2.5.0
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    namespaceOverride: monitoring
  
  node-exporter:
    enabled: true
    image:
      repository: prom/node-exporter
      tag: v1.3.1
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9100
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    namespaceOverride: monitoring
  
  # Global scheduling options
nodeSelector: {}

tolerations: []

affinity: {}
