my-chart:
  replicaCount: 1
  image:
    repository: prom/prometheus
    tag: "v2.33.1"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 9090

  resources:
    requests:
      memory: "1Gi"
      cpu: "50m"
    limits:
      memory: "2Gi"

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: local-storage
    accessMode: ReadWriteOnce
